spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_db
    username: car_user
    password: car_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: none
      password: none

server:
  servlet:
    session:
      timeout: 2m

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
